[package]
name = "ocr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
leptess = "0.14"
poppler = "0.6"
image = "0.25"
tempfile = "3.10"
dotext = "0.1.1"
html2text = "0.16.6"

[dev-dependencies]
tokio = { version = "1.37", features = ["full"] }
