[package]
name = "embed"
version = "0.1.0"
edition = "2021"

[features]
default = []
cuda = ["ort/cuda"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
fastembed = "5"
ort = "2.0.0-rc.11"

[dev-dependencies]
tokio = { version = "1.37", features = ["full"] }
